### ISSUE TITLE
想问一下用镜像链接如何使用本项目

### ISSUE THREAD

**Issue by wrongww78319** [quenlowi/ao3down#2]
首先感谢上传项目，让我有机会可以批量下载ao3的文
但是由于条件限制，我只能使用镜像链接“https://isnull.info/works/search?work_search%5Bquery%5D=%E5%93%8D%E6%AC%A3”
我自己尝试了一下可能是我操作的问题，不能运行，想问一下该如何操作，谢谢！！
（纯小白抱歉）

**Comment by RoxanneRR** [comment]
你好，你用的是py文件还是exe？

**1. py比较简单，你只需要修改23行和37行**

第23行的ao3url，是所连接的网站。可以是ao3官方网址也可以是镜像。
现在我那里填的`https://nightalk.cc`本身就是镜像，你可以不修改它或者换成你的镜像。

第37行的surlist，是具体要爬的链接。你得把37行改成你自己的链接。
surlist应该使用列表格式，也就是 `surlist=["链接","链接","链接"]` 这个格式。
把你的链接填进去，得到： `surlist=["https://isnull.info/works/search?work_search%5Bquery%5D=%E5%93%8D%E6%AC%A3%E2%80%9D"]`


但是，我看了一下你的这个镜像有防火墙，可能会阻止爬取。如果爬取失败的话，你可以试着换一个镜像，推荐就换成我在用的`https://nightalk.cc/`则你的链接填进去变成
`surlist=["https://nightalk.cc/works/search?work_search%5Bquery%5D=%E5%93%8D%E6%AC%A3%E2%80%9D"]`


如果你要爬多个就按照上面的示范继续添加。


**2. exe同理**
你点击exe生成txt，然后按照上面的格式改就行。
但是我好久之前传的exe了，都忘了封装了什么代码。现在我手边没有电脑，不好试，如果你按照上面的方法解决不了问题，就有点麻烦。

**Comment by wrongww78319** [comment]
刚刚尝试了一下，发现运行完之后生成的文件夹里面没有东西，空的

**Comment by RoxanneRR** [comment]
①如果你使用的是py文件，把你修改的surllist和编译器报错traceback发上来我看看
②如果你使用的是exe文件，你可以尝试在cmd窗口中运行该exe文件，以获取闪退前的报错信息，然后把你修改的surllist和cmd窗口显示的报错信息发我看看

**Comment by wrongww78319** [comment]
![~97Z(8~`SQ0 U%TC`C`4SOS](https://github.com/RoxanneRR/ao3down/assets/116002907/915353a8-ce09-49ac-afe1-b72501c9e35d)
![0KH}867$NDN)HYCE}) EPIP](https://github.com/RoxanneRR/ao3down/assets/116002907/15c95ddf-066e-4d60-a262-7b81a69ff967)

**Comment by wrongww78319** [comment]
以下是标红的部分，我发现好像不能发图过去实在不好意思
Traceback (most recent call last):
  File "C:\Users\wohuishiyong\Desktop\ao3down-main\ao3down-main\ao3down.py", line 277, in <module>
    main_moresurl(surlist)
  File "C:\Users\wohuishiyong\Desktop\ao3down-main\ao3down-main\ao3down.py", line 66, in main_moresurl
    workdiclist,thepath = theseries(surl)
  File "C:\Users\wohuishiyong\Desktop\ao3down-main\ao3down-main\ao3down.py", line 165, in theseries
    aut = worklist[i].find('a',{"rel":"author"}).string
AttributeError: 'NoneType' object has no attribute 'string'



37行修改部分在下面

surlist=["https://nightalk.cc/works/search?work_search%5Bquery%5D=%E5%BD%AA%E6%AC%A3"]

仅修改了“”内的部分

**Comment by 3tradewind** [comment]
作者您好，我在运行后一直停留在这一步，除了txt文件的网址没有做其它修改，您可以指点一下吗，感谢！
![image](https://github.com/RoxanneRR/ao3down/assets/78865844/f7ac1579-58a5-4e07-9c1e-904b2a575424)
